name: Chunky
version: ${project.version}
main: org.popcraft.chunky.Chunky
api-version: "1.14"
authors: [pop4959]
description: Pre-generates chunks, quickly, efficiently, and safely
commands:
  chunky:
    description: Generates chunks
    permission: chunky.chunky
    usage: /chunky
permissions:
  chunky.chunky:
    description: Generates chunks
    default: op
